web/web/urls.py
from django.contrib import admin
from django.urls import path
from  django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("webapp.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          docoment_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/webapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path
app_name='webapp'
urlpatterns = [

   path('',views.index,name='index'),
   path('movie/<int:movie_id>/',views.detail,name='detail'),
   path('add/',views.add_movie,name='add_movie'),
   path('update/<int:id>/',views.update,name='update'),
   path('delete/<int:id>/',views.delete,name='delete')


]

web/webapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallary')


    def __str__(self):
        return self.name

web/webapp/forms.py
from django import forms
from  .models import movie

class movieforms(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

web/webapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from  . models import movie
from  .forms import movieforms
# Create your views here.
# def demo(request):
#     return HttpResponse("hello world")
# def app(request):
#     return render(request,"index.html")
def index(request):
    Movie=movie.objects.all()
    context={
        'movie_list':Movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    Movie=movie.objects.get(id=movie_id)

    return render(request,'details.html',{'Movie':Movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        Movie1=movie(name=name,desc=desc,year=year,img=img)
        Movie1.save()

    return render(request,'add.html')

def update(request,id):
    mov=movie.objects.get(id=id)
    form=movieforms(request.POST or None, request.FILES,instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

web/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="desc" placeholder="enter movie desc">
    <input type="number" name="year" placeholder="enter movie year">
    <input type="file" name="img">
    <input type="submit">


</form>
{% endblock %}

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>netflix</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-light bg-primary justify-content-between">
  <a class="navbar-brand">NETFLIX MOVIES</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search movies" aria-label="Search">
    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
<!-- Image and text -->
<!--<nav class="navbar navbar-dark bg-dark">-->
<!--  <a class="navbar-brand" href="#">-->
<!--    NETFLIX MOVIES-->
<!--  </a>-->
<!--</nav>-->
{% block body %}
{% endblock %}
</body>
</html>

web/templates/delete.html
<form method="POST">
    {% csrf_token %}
    are you want to delete this mov
    <input type="submit">
</form>

web/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{Movie.img.url}}"width="400px"height="400px">
        </div>

<div class="col-md-3">
    <h4> {{Movie.name}}</h4>
    {{Movie.desc}}<br>
    {{Movie.year}}
    <br>
<a class="btn btn-warning" href="{% url 'webapp:update' Movie.id %}">update</a>


<a class="btn btn-danger" href="{% url 'webapp:delete' Movie.id %}">delete</a>
</div>


{% endblock %}
 </div>

</div>

web/templates/edit.html
<form method="POST" ENCTYPE="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

web/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">{% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" >
                 <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap"width="200px" height="200px">
                  <div class="card-body" >
                      <h5 class="card-title"  >{{i.name}}</h5>
                      <p class="card-text" style="width:12rem:">{{i.desc}}</p>
                      <a href="{% url 'webapp:detail' i.id %}" class="btn btn-secondary">watch movie</a>

  </div>
</div>
        </div>
        {% endfor %}
    </div>
    <br><a href="{% url 'webapp:add_movie' %}" class="btn btn-success">click here to add movie</a>
</div>




{% endblock %}